source 'http://rubygems.org'


gem 'data_mapper', '~> 1.2.0'
# gem 'dm-mysql-adapter'
# gem 'dm-postgres-adapter'
gem 'dm-sqlite-adapter', '~> 1.2.0'
gem 'sinatra', '~> 1.3.1'  
gem 'vesper', :require => false
gem 'whenever', '~> 0.7.0', :require => false
  

Dir["./plugins/**/Gemfile"].each {|gemfile| self.send(:eval, File.open(gemfile, 'r').read)}