# Load the application
  require './loader.rb'

# Load plugin Rake tasks
  Dir["./plugins/**/tasks/*"].each {|file| require file}

# Load your custom Rake tasks
  Dir["./tasks/**/*"].each {|file| require file}