# Use RubyGems to find and download gems
  source 'http://rubygems.org'


# For databases and model classes
  gem 'data_mapper', '~> 1.2.0'
  # gem 'dm-mysql-adapter'
  # gem 'dm-postgres-adapter'
  gem 'dm-sqlite-adapter', '~> 1.2.0'

# For sending email
  gem 'pony', '~> 1.4'

# For route handling
  gem 'sinatra', '~> 1.3.1'

# For sending text messages
  gem 'twiliolib', '~> 2.0.7'

# For writing cron jobs in Ruby
  gem 'whenever', '~> 0.7.0', :require => false
  
# Load gems from plugins
  Dir["./plugins/**/Gemfile"].each {|gemfile| self.send(:eval, File.open(gemfile, 'r').read)}